### ISSUE TITLE
pip requirements

### ISSUE THREAD

**Issue by LarsVomMars** [Schrolli91/BOSWatch#444]
Document all required python packages in a requirements.txt or any other way.

E.g.: for the Telegram plugin the *requests* package is required which isn't installed by default and i didn't find any documentation in the wiki - hmu if there is a documentation for it. ;)

**Comment by Schrolli91** [comment]
BOSWatch should install all needed packages with the installer script.
All the other plugins are not automated installed because nobody uses all of the plugins.

Each plugin has a comment with the requirements for its usage - see:
https://github.com/Schrolli91/BOSWatch/blob/6054a38ff56a978ae5df730543fb844c68e8122d/plugins/Telegram/Telegram.py#L7

BTW: The wiki is a little bit outdated because we're working on BOSWatch 3 atm

**Comment by LarsVomMars** [comment]
Oh sorry, must have read over this line :c 

But on the other hand couldn't you create a plugin specific requirements.txt in their regarding directories, so users could install them when using the plugin?

**Comment by Schrolli91** [comment]
Sure, i think thats a helpful idea - if you want, feel free to put a pull request with this changes.

**Comment by LarsVomMars** [comment]
I'll get to it later today

**Comment by LarsVomMars** [comment]
So i think this is solved by the pull request. :)
