### ISSUE TITLE
Q: MySQL Plugin: Timestamp / Funtionschar Format ändern

### ISSUE THREAD

**Issue by ThomasF88** [Schrolli91/BOSWatch#93]
Guten Abend, ist es möglich das Format des Timestamps beim MySQL Plugin zu ändern?
Sprich, anstatt "2016-05-12 16:48:05" folgendes in die DB zu schreiben:
"12.05.2016 - 16:48"?

Und, fast das gleiche beim Funktionschar, bzw. der Subric.
Ist es möglich anstatt ABCD "Übersetzungen", wie "Sirene, Kleinalarm usw." einzupflegen, dass diese gleich in die DB geschrieben werden?

Momentan gehe ich den Umweg und lasse per PHP übersetzen, was aber natürlich nicht das Gelbe vom Ei ist.

**Comment by Smith-fms** [comment]
Quick and dirty:
Vorm schreiben in die DB einfach ein str-replace in die py schreiben. Im MySQL Modul. 
Ansonsten verstehe ich nicht warum man nicht einfach die Ausgabe übersetzten lässt. Das wäre sinnvoller.
Die Bedeutungen sind überall unterschiedlich.
Und es ist üblich, auch aufgrund der besseren Sortierbarkeit die englische Schreibform beim Datum zu nehmen.

VG
ReneGuten Abend, ist es möglich das Format des Timestamps beim MySQL Plugin zu ändern?
Sprich, anstatt "2016-05-12 16:48:05" folgendes in die DB zu schreiben:
"12.05.2016 - 16:48"?

Und, fast das gleiche beim Funktionschar, bzw. der Subric.
Ist es möglich anstatt ABCD "Übersetzungen", wie "Sirene, Kleinalarm usw." einzupflegen, dass diese gleich in die DB geschrieben werden?

Momentan gehe ich den Umweg und lasse per PHP übersetzen, was aber natürlich nicht das Gelbe vom Ei ist.

---

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/Schrolli91/BOSWatch/issues/93

**Comment by ThomasF88** [comment]
Vielen Dank! :)
Allerdings verstehe ich nicht ganz, wieso sich das englische Datum besser sortieren lässt?
Bzw. hast Du zu diesem Punkt eine Idee, oder einen Codeschnipsel?
Bin leider ziemlich neu auf dem Gebiet :sa:

**Comment by K3vP0** [comment]
Moin,

also: ein Datum sollte in einer MySQL Tabelle grundsätzlich auch den Typ
Date haben.
Siehe:
https://www.google.de/url?q=http://www.w3schools.com/sql/func_date_format.asp&sa=U&ved=0ahUKEwigw4-7rdXMAhUMFSwKHXTMBvYQFggRMAE&sig2=J63qo5zxlZxACNBUin_PqQ&usg=AFQjCNF3EzVdV9GVT4jJU69IHtHpDuM-ww

Mit den unterschiedlichen Funktionen hat es auch seine Berechtigung siehe
oben.

Um das Verständnis der Sortierung ein wenig zu festigen Spiele doch einfach
mal folgendes Beispiel durch:

Du hast 3 Freunde, die 3 Freunde haben am

15.1.80
30.12.81
Und am
1.5.79 Geburtstag.

Sortiere diese mal nach Alter, einfacher ist es wenn du folgende Daten
deinem Computer fütterst:

80/01/15
81/12/30
79/05/01

Dann muss er einfach nur von größter zu kleiner Zahl sortieren.

;)
Grüße
Kevin
Am 12.05.2016 22:16 schrieb "ThomasF88" notifications@github.com:

Vielen Dank! :)
Allerdings verstehe ich nicht ganz, wieso sich das englische Datum besser
sortieren lässt?
Bzw. hast Du zu diesem Punkt eine Idee, oder einen Codeschnipsel?
Bin leider ziemlich neu auf dem Gebiet [image: :sa:]

**Comment by ThomasF88** [comment]
Oh, okay, vielen Dank! :)
Das klingt sehr plausibel, aber da kam ich echt nicht drauf. :D
allerdings sortiere ich die Ausgabe per ID und das deutsche Format würde mir um einiges besser gefallen.

Nur bekomme ich das in meinem Skript einfach nicht hin.
Wo muss ich denn das Date Format ändern?

Ich bin einfach zu blöd :s

**Comment by K3vP0** [comment]
http://www.gidf.de/php+mysql+date+format

Im PHP Quellcode ...
Am 12.05.2016 22:44 schrieb "ThomasF88" notifications@github.com:

**Comment by ThomasF88** [comment]
Danke Dir, wie ich es verwende ist mir klar.
Aber ich verstehe nicht, wo / wann boswatch das in die Tabelle schreibt.

Also ich stehe auf dem Schlauch.
Ich habe ja sämtliche Dateien im .py Format und die im /plugin/MySQL Ordner schreibt doch nichts in die DB?

**Comment by Schrolli91** [comment]
Das Datum in dem Format hat schon seine Berechtigung, immerhin wird es in ein DateTime MySQL Feld geschrieben, und das erwartet nunmal dieses englische Format. Über die Ausgabe in PHP kann man ja aber das Datum wieder in ein gewünschtes Format umwandeln.

**Comment by Schrolli91** [comment]
Da es keine weiteren Kommentare dazu gibt, werde ich das Issue schließen.

Die Daten müssen, da die MySQL Tabelle nun mal ein DateTime Feld ist, im englischen Format standard mäßig so übergeben werden. Für die Formatierung bei der Ausgabe kann man sich in PHP mittels 'echo $date->format('Y-m-d H:i:s');' behelfen.
